<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Gloria Lowery">
<meta name="dcterms.date" content="2026-04-13">
<meta name="description" content="A non-parametric supervised learning algorithm ">

<title>Using the Machine Learning Algorithm K-Nearest Neighbors to Detect Patients with Diabetes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-075dce6384a7aff99b092f416a9d68fa.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span style="color: #0366D6;">Using the Machine Learning Algorithm K-Nearest Neighbors to Detect Patients with Diabetes</span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>

<div>
  <div class="description">
    A non-parametric supervised learning algorithm<br>
    <hr>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Gloria Lowery </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 13, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<hr>
<p><a href="link" class="external" target="_blank">Presentation</a></p>
<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>When give data we typically want to make sense of what the data is telling us. Machine learning algorithms enable us to do just that. They are mathematical and statistical instructions that computers learn to make sense of a raw dataset.</p>
<p>One such learning algorithm that we will look at is K-Nearest Neighbor. It is considered a “non-parametric supervised learning algorithm.” Non-parametric meaning it makes few or no assumptions about the underlying shape or distribution of data. Supervised, as in, it learns from labeled data (input that has a corresponding output) with a goal to predict outcomes for new, unseen data.</p>
<p>The main goal of the K-Nearest Neighbors(KNN) algorithm is to predict the classification or numerical value of a new data point based on how similar it is to its closest neighbors. In this paper we will discuss the concept and underlying methodology of KNN, it’s strengths and limitations, as well as its real-world applications such as in business and medicine. Specifically, applying the KNN algorithm to identify diabetes within a group of subjects who were studied in order to understand the prevalence of obesity, diabetes, and other cardiovascular risk factors.</p>
<p>You can think of KNN as <strong><em>“birds of a feather flock together.”</em></strong></p>
</section>
<section id="method" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Method</h1>
<p>The K-Nearest Neighbors (KNN) algorithm is one of the simplest and most intuitive supervised machine learning methods used for both classification (assigning a category) and regression (predicting a value). It is a non-parametric, supervised machine learning method used for both classification and regression. It requires two instances for it to achieve its goal 1) a distance metric and 2) defining K<span class="citation" data-cites="IBM2024">(<a href="#ref-IBM2024" role="doc-biblioref"><span>“What Is the k-Nearest Neighbor (KNN) Algorithm?”</span> 2024</a>)</span>. Its methodology relies on the proximity principle, assuming that similar data points exist in close proximity within a feature space.</p>
<p>Take a look at the following photo.</p>
<center>
<div id="fig-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="KnnClassification.svg.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: K-Nearest Neighbor Visual Representation (Image Source: ©Wikipedia2019)
</figcaption>
</figure>
</div>
</center>
<p>When determining how to classify the green dot as either a blue square or red triangle, we will look at its neighbors - specifically the ones closest to it. Here, if we chose to look at three of its closest neighbors (k=3) we are looking at the area within the inner solid circle. We see that the majority of its neighbors are red triangles so we would classify the green dot as a red triangle. However, if we’re looking within the area of dashed circle, we see three blue squares vs two red triangles so the green dot would then be classified as a blue square.</p>
<p>But KNN is a bit more complex than this.</p>
<section id="core-steps-of-the-knn-methodology" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="core-steps-of-the-knn-methodology"><span class="header-section-number">2.1</span> Core Steps of the KNN Methodology</h2>
<ol type="1">
<li><p>Defining the Parameter ‘K’: Like mentioned, when defining or selecting k, we are selecting the number of nearest neighbors to consider to determine the classification of a query point. For example, K=1, means it will be assigned to the same class as its single nearest neighbor. Choosing K depends on the input data. For example, data with more outliers performs much better with higher k values. We also want to choose an odd number for k to minimize the chances of ties in classification. <span class="citation" data-cites="zhang2018">(<a href="#ref-zhang2018" role="doc-biblioref">S. Zhang and Wang 2018</a>)</span></p></li>
<li><p>Calculating Distance: When a new, unlabeled data point is introduced, the algorithm calculates its distance to every other point in the training dataset. The distance metric measures the distance between the query point(s) and other data points. It can be calculated using a variety of formulas. For example, either Euclidean distance, Manhattan distance, Minkowski, or Hamming distance, and we can visualize this using Voronezh diagrams like above. <span class="citation" data-cites="VisuallyExplained2025">(<a href="#ref-VisuallyExplained2025" role="doc-biblioref"><span>“K-Nearest Neighbors (KNN) in 3 Min”</span> 2025</a>)</span></p></li>
</ol>
<p><em>Euclidean Distance</em>: Most commonly used. Measures the “straight-line” path between points; best for continuous data.</p>
<p><span class="math display">\[
D_{euclidean}(x_1, x_2) = \sqrt{\sum_{i = 1}^{n}{((x_1)_i - (x_2)_i)^2}}
\]</span></p>
<p><em>Manhattan Distance</em>: Calculates the sum of absolute differences, similar to navigating a grid (taxicab geometry).</p>
<span class="math display">\[
D_{manhattan}(x_1, x_2) = \sum_{i = 1}^{n}|((x_1)_i - (x_2)_i)|
\]</span> <em>Minkowski Distance</em>: A generalized formula that can represent both Euclidean (p=1) and Manhattan (p=2) distances. <span class="math display">\[
D_{Minkowski}(X,Y) = \sum_{i = 1}^{n}|x_i - y_i|^p
\]</span> <em>Hamming Distance</em>: Used for categorical or string variables to identify where vectors do not match.
<center>
<div id="fig-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Hamming%20Distance.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Hamming Distance XOR (Image Source: ©An2021. Inspired from <span class="citation" data-cites="An2021">(<a href="#ref-An2021" role="doc-biblioref">An 2021</a>)</span>)
</figcaption>
</figure>
</div>
</center>
<ol start="3" type="1">
<li><p>Identify Neighbors: Combining steps 1 and 2. We defined k, we determined distance based on our metric distance formula. Now we sort and select the points with the smallest distance values to the new query point.</p></li>
<li><p>Aggregate results based on the goal.</p></li>
</ol>
<ul>
<li><p>Classification: The new point is assigned the class that appears most frequently among its k neighbors (majority or plurality voting). Like the example above, we had mostly blue squares within the vicinity to the query point aka the green dot so it is most likely also a blue square.</p></li>
<li><p>Regression: The algorithm predicts a continuous value by taking the average (mean) or median of the k neighbors’ target values.</p></li>
</ul>
</section>
<section id="key-characteristics-of-knn" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="key-characteristics-of-knn"><span class="header-section-number">2.2</span> Key Characteristics of KNN</h2>
<p>Lazy Learner: KNN is considered a “lazy learner” because it does not have a distinct training phase. It simply stores the training data and defers all computation until a prediction is requested.</p>
<p>Non-Parametric: It makes no prior assumptions about the underlying distribution of the data, making it flexible for complex datasets.</p>
<p>Sensitivity to Scale: Because it relies on distance, features with larger magnitudes can disproportionately influence results. Therefore, feature scaling (standardization or normalization) is a critical preprocessing step.<span class="citation" data-cites="xing2020">(<a href="#ref-xing2020" role="doc-biblioref"><span>“Medical Health Big Data Classification Based on KNN Classification Algorithm”</span> 2020</a>)</span></p>
<p>Finding the Optimal ‘K’: The value of k is often determined using the Elbow Method or Cross-Validation, where multiple k values are tested to find the one that minimizes the error rate without overfitting or underfitting. Analysts typically choose an odd number for k to prevent ties in classification (like if we had equal red triangles and blue squares what then?). In our example, we will be using cross-validation to determine the value of ‘k’. In cross validation, the dataset is divided by kfolds. Where at each iteration each fold is used once as test data and the remaining fold is used as training data, the process is repeated until all data is evaluated. <span class="citation" data-cites="Tembusai2021">(<a href="#ref-Tembusai2021" role="doc-biblioref"><span>“K-Nearest Neighbor with k-Fold Cross Validation and Analytic Hierarchy Process on Data Classification”</span> 2021</a>)</span></p>
</section>
<section id="strengths-of-knn" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="strengths-of-knn"><span class="header-section-number">2.3</span> Strengths of KNN</h2>
<p>1.Easy to implement/learn. There are also few hyper parameters - just the distance and k value.</p>
<ol start="2" type="1">
<li>It’s also adaptable. It adjusts easily to new training data since all training data is stored into memory. But similarly, because of that, it doesn’t scale well. As the data set grows, the algorithm becomes less efficient due to increasing computational complexity, which compromises overall model performance.</li>
</ol>
</section>
<section id="weaknesses-of-knn" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="weaknesses-of-knn"><span class="header-section-number">2.4</span> Weaknesses of KNN</h2>
<ol type="1">
<li><p>As mentioned, it can be considered a “lazy algorithm” meaning it stores all training data and defers the computation to the time of classification, increasing memory usage and leads to slower processing compared to other methods of classifying. In other words, it does not build the model beforehand. It instead stores the data and makes predictions on demand.</p></li>
<li><p>KNN also has what’s called the “Curse of Dimensionality.” It does not perform well with high dimensional data inputs. On a 2D xy graph it works fine but if we wanted to classify according to color, size, weight, etc. then the data points become sparse in higher dimensions and the distance between points become too similar for KNN to find meaningful neighbors. This leads to what’s called the “peaking phenomenon.” The peaking phenomenon occurs after reaching the optimal number of features - any more just increases noise and increases classification errors especially when the sample size is small. Feature selection and dimensionality reduction techniques can help minimize “curse of dimensionality” but we need to be careful.</p></li>
<li><p>Another weakness is overfitting. Low k values can overfit the data. High values tend to smooth out prediction values since average values over a greater are or neighborhood. <span class="citation" data-cites="zhang2022">(<a href="#ref-zhang2022" role="doc-biblioref">Zhang 2022</a>)</span></p></li>
</ol>
</section>
<section id="uses-of-the-knn-algorithm" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="uses-of-the-knn-algorithm"><span class="header-section-number">2.5</span> Uses of the KNN Algorithm</h2>
<p>When it comes to uses, we can use the KNN algorithm for simple recommendation systems. Data free processing is most commonly used because it’s helpful for data sets with missing values because it estimates values using process called missing data imputation. KNN is actually most often used in finance like stock market forecasting, currency exchange rate, money laundering analysis. But it is also used in health care. For example, risk of heart attacks and prostate cancer by calculating most likely gene expression. In this paper we will apply the KNN algorithm to a data set of potential diabetic patients.<span class="citation" data-cites="Nain2023">(<a href="#ref-Nain2023" role="doc-biblioref"><span>“Medical Image Prediction for Diagnosis of Breast Cancer Using Machine Learning”</span> 2021</a>)</span></p>
</section>
</section>
<section id="analysis-and-results" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Analysis and Results</h1>
<section id="data-description" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="data-description"><span class="header-section-number">3.1</span> Data Description</h2>
<p>These data sets are courtesy of Dr John Schorling, Department of Medicine, University of Virginia School of Medicine.<span class="citation" data-cites="Schorling1997">(<a href="#ref-Schorling1997" role="doc-biblioref">Schorling JB 1997</a>)</span> The data consist of 19 variables on 403 subjects from 1046 subjects who were interviewed in a study to understand the prevalence of obesity, diabetes, and other cardiovascular risk factors in central Virginia for African Americans. According to Dr John Hong, Diabetes Mellitus Type II (adult onset diabetes) is associated most strongly with obesity. The waist/hip ratio may be a predictor in diabetes and heart disease. DM II is also associated with hypertension - they may both be part of “Syndrome X”. The 403 subjects were the ones who were actually screened for diabetes. Glycosolated hemoglobin &gt; 7.0 is usually taken as a positive diagnosis of diabetes. <span class="citation" data-cites="Willems1997">(<a href="#ref-Willems1997" role="doc-biblioref">Willems JP 1997</a>)</span></p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(df))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 9%">
<col style="width: 2%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 3%">
<col style="width: 3%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Patient.number</th>
<th style="text-align: right;">Cholesterol</th>
<th style="text-align: right;">Glucose</th>
<th style="text-align: right;">HDL.Chol</th>
<th style="text-align: right;">Chol.HDL.ratio</th>
<th style="text-align: right;">Age</th>
<th style="text-align: left;">Gender</th>
<th style="text-align: right;">Height</th>
<th style="text-align: right;">Weight</th>
<th style="text-align: right;">BMI</th>
<th style="text-align: right;">Systolic.BP</th>
<th style="text-align: right;">Diastolic.BP</th>
<th style="text-align: right;">waist</th>
<th style="text-align: right;">hip</th>
<th style="text-align: right;">Waist.hip.ratio</th>
<th style="text-align: left;">Diabetes</th>
<th style="text-align: right;">…17</th>
<th style="text-align: right;">…18</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">193</td>
<td style="text-align: right;">77</td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">3.9</td>
<td style="text-align: right;">19</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">61</td>
<td style="text-align: right;">119</td>
<td style="text-align: right;">22.5</td>
<td style="text-align: right;">118</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">0.84</td>
<td style="text-align: left;">No diabetes</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">146</td>
<td style="text-align: right;">79</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">3.6</td>
<td style="text-align: right;">19</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">135</td>
<td style="text-align: right;">26.4</td>
<td style="text-align: right;">108</td>
<td style="text-align: right;">58</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">0.83</td>
<td style="text-align: left;">No diabetes</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">217</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">54</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">20</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">67</td>
<td style="text-align: right;">187</td>
<td style="text-align: right;">29.3</td>
<td style="text-align: right;">110</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">0.89</td>
<td style="text-align: left;">No diabetes</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">226</td>
<td style="text-align: right;">97</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">3.2</td>
<td style="text-align: right;">20</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">64</td>
<td style="text-align: right;">114</td>
<td style="text-align: right;">19.6</td>
<td style="text-align: right;">122</td>
<td style="text-align: right;">64</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: left;">No diabetes</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">164</td>
<td style="text-align: right;">91</td>
<td style="text-align: right;">67</td>
<td style="text-align: right;">2.4</td>
<td style="text-align: right;">20</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">141</td>
<td style="text-align: right;">20.2</td>
<td style="text-align: right;">122</td>
<td style="text-align: right;">86</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: left;">No diabetes</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">170</td>
<td style="text-align: right;">69</td>
<td style="text-align: right;">64</td>
<td style="text-align: right;">2.7</td>
<td style="text-align: right;">20</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">64</td>
<td style="text-align: right;">161</td>
<td style="text-align: right;">27.6</td>
<td style="text-align: right;">108</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: left;">No diabetes</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>As shown, we have variables we do not need/want including empty columns. We’ll select the non-demographic columns to begin and create a reduced data set. The new table below shows the first 6 rows of our reduced data set.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df_reduced <span class="ot">&lt;-</span> df[<span class="fu">c</span>(<span class="st">"Diabetes"</span>, <span class="st">"Cholesterol"</span>, <span class="st">"Glucose"</span>, <span class="st">"BMI"</span>, <span class="st">"Waist.hip.ratio"</span>, <span class="st">"HDL.Chol"</span>, <span class="st">"Chol.HDL.ratio"</span>, <span class="st">"Systolic.BP"</span>, <span class="st">"Diastolic.BP"</span>, <span class="st">"Weight"</span>)]</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(df_reduced))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 7%">
<col style="width: 4%">
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Diabetes</th>
<th style="text-align: right;">Cholesterol</th>
<th style="text-align: right;">Glucose</th>
<th style="text-align: right;">BMI</th>
<th style="text-align: right;">Waist.hip.ratio</th>
<th style="text-align: right;">HDL.Chol</th>
<th style="text-align: right;">Chol.HDL.ratio</th>
<th style="text-align: right;">Systolic.BP</th>
<th style="text-align: right;">Diastolic.BP</th>
<th style="text-align: right;">Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No diabetes</td>
<td style="text-align: right;">193</td>
<td style="text-align: right;">77</td>
<td style="text-align: right;">22.5</td>
<td style="text-align: right;">0.84</td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">3.9</td>
<td style="text-align: right;">118</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">119</td>
</tr>
<tr class="even">
<td style="text-align: left;">No diabetes</td>
<td style="text-align: right;">146</td>
<td style="text-align: right;">79</td>
<td style="text-align: right;">26.4</td>
<td style="text-align: right;">0.83</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">3.6</td>
<td style="text-align: right;">108</td>
<td style="text-align: right;">58</td>
<td style="text-align: right;">135</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No diabetes</td>
<td style="text-align: right;">217</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">29.3</td>
<td style="text-align: right;">0.89</td>
<td style="text-align: right;">54</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">110</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">187</td>
</tr>
<tr class="even">
<td style="text-align: left;">No diabetes</td>
<td style="text-align: right;">226</td>
<td style="text-align: right;">97</td>
<td style="text-align: right;">19.6</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">3.2</td>
<td style="text-align: right;">122</td>
<td style="text-align: right;">64</td>
<td style="text-align: right;">114</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No diabetes</td>
<td style="text-align: right;">164</td>
<td style="text-align: right;">91</td>
<td style="text-align: right;">20.2</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">67</td>
<td style="text-align: right;">2.4</td>
<td style="text-align: right;">122</td>
<td style="text-align: right;">86</td>
<td style="text-align: right;">141</td>
</tr>
<tr class="even">
<td style="text-align: left;">No diabetes</td>
<td style="text-align: right;">170</td>
<td style="text-align: right;">69</td>
<td style="text-align: right;">27.6</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">64</td>
<td style="text-align: right;">2.7</td>
<td style="text-align: right;">108</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">161</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The table below now shows a description of each of our variables to be used.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(vars)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Variables</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Diabetes</td>
<td style="text-align: left;">Yes/No</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cholesterol</td>
<td style="text-align: left;">Numeric</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Glucose</td>
<td style="text-align: left;">Numeric</td>
</tr>
<tr class="even">
<td style="text-align: left;">BMI</td>
<td style="text-align: left;">Numeric</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Waist.hip.ratio</td>
<td style="text-align: left;">Waist to Hip Ratio</td>
</tr>
<tr class="even">
<td style="text-align: left;">HDL.Chol</td>
<td style="text-align: left;">Numeric</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chol.HDL.ratio</td>
<td style="text-align: left;">Cholesterol to HDL ratio</td>
</tr>
<tr class="even">
<td style="text-align: left;">Systolic.BP</td>
<td style="text-align: left;">Systolic Blood Pressure</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diastolic.BP</td>
<td style="text-align: left;">Diastolic Blood Pressure</td>
</tr>
<tr class="even">
<td style="text-align: left;">Weight</td>
<td style="text-align: left;">Numeric</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="preparing-the-data" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="preparing-the-data"><span class="header-section-number">3.2</span> Preparing the Data</h2>
<p>Like mentioned, kNN is sensitive to scaling (of the variables). So it is helpful to first standardize the variables. We do this using the preProcess function of the caret package:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>preproc_reduced <span class="ot">&lt;-</span> <span class="fu">preProcess</span>(df_reduced[,<span class="dv">2</span><span class="sc">:</span><span class="dv">10</span>], <span class="at">method =</span> <span class="fu">c</span>(<span class="st">"scale"</span>, <span class="st">"center"</span>))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>df_standardized <span class="ot">&lt;-</span> <span class="fu">predict</span>(preproc_reduced, df_reduced[, <span class="dv">2</span><span class="sc">:</span><span class="dv">10</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Now we have scaled and centered values for our data.frame.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df_standardized)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Cholesterol          Glucose              BMI          Waist.hip.ratio   
 Min.   :-2.89327   Min.   :-1.10298   Min.   :-2.0566   Min.   :-2.75070  
 1st Qu.:-0.63204   1st Qu.:-0.48958   1st Qu.:-0.7083   1st Qu.:-0.70186  
 Median :-0.09472   Median :-0.32229   Median :-0.1478   Median :-0.01891  
 Mean   : 0.00000   Mean   : 0.00000   Mean   : 0.0000   Mean   : 0.00000  
 3rd Qu.: 0.48738   3rd Qu.: 0.00765   3rd Qu.: 0.5301   3rd Qu.: 0.66403  
 Max.   : 5.27849   Max.   : 5.16117   Max.   : 4.0940   Max.   : 3.53241  
    HDL.Chol       Chol.HDL.ratio     Systolic.BP        Diastolic.BP     
 Min.   :-2.2146   Min.   :-1.7417   Min.   :-2.06187   Min.   :-2.61441  
 1st Qu.:-0.7099   1st Qu.:-0.7627   1st Qu.:-0.66201   1st Qu.:-0.61414  
 Median :-0.2469   Median :-0.1869   Median :-0.04958   Median :-0.09555  
 Mean   : 0.0000   Mean   : 0.0000   Mean   : 0.00000   Mean   : 0.00000  
 3rd Qu.: 0.5054   3rd Qu.: 0.5041   3rd Qu.: 0.47537   3rd Qu.: 0.49712  
 Max.   : 4.0357   Max.   : 8.5081   Max.   : 4.93740   Max.   : 3.01598  
     Weight       
 Min.   :-1.9404  
 1st Qu.:-0.6721  
 Median :-0.1091  
 Mean   : 0.0000  
 3rd Qu.: 0.5591  
 Max.   : 3.6526  </code></pre>
</div>
</div>
<p>Apply those scaled and centered values to our data using the bind_cols method from dpylr to normalize all of our data.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df_stdize <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(<span class="at">Diabetes =</span> df_reduced<span class="sc">$</span>Diabetes, df_standardized)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Now we have a data set which will work well for KNN!</p>
</section>
<section id="using-the-knn-model" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="using-the-knn-model"><span class="header-section-number">3.3</span> Using the KNN Model</h2>
<p>First, we create a test/train split so that we can train a KNN model. We will use the createDataPartition from caret to randomly select 80% of the data to use for the training set and 20% of the data to use for the test set. Then, create two different data frames using partition point returned by createDataPartition.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># "p" indicates how much of the data should go into the first created partition</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>param_split<span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(df_stdize<span class="sc">$</span>Diabetes, <span class="at">times =</span> <span class="dv">1</span>, <span class="at">p =</span> <span class="fl">0.8</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>train_df <span class="ot">&lt;-</span> df_stdize[param_split, ]</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>test_df <span class="ot">&lt;-</span> df_stdize[<span class="sc">-</span>param_split, ]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Now we “train” the KNN.</p>
<p>The trainControl method is a helper function for all the nuances of the KNN train method. It allows you to easily set up the KNN training parameters.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>trnctrl_df <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>method: This is the resampling method used. Using “cv” or cross validation. number: The number of folds because we’re using cv.</p>
<p>Now we will use all our variables to predict Diabetes. Then specify the training data, that we’re training a KNN, and pass the training hyperparameters that we built with trainControl.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>model_knn_df <span class="ot">&lt;-</span> <span class="fu">train</span>(Diabetes <span class="sc">~</span> ., <span class="at">data =</span> train_df, <span class="at">method =</span> <span class="st">"knn"</span>, </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">trControl =</span> trnctrl_df, </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">tuneLength =</span> <span class="dv">10</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>model_knn_df</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>k-Nearest Neighbors 

312 samples
  9 predictor
  2 classes: 'Diabetes', 'No diabetes' 

No pre-processing
Resampling: Cross-Validated (10 fold) 
Summary of sample sizes: 281, 280, 281, 282, 281, 281, ... 
Resampling results across tuning parameters:

  k   Accuracy   Kappa    
   5  0.9166129  0.5860773
   7  0.9198387  0.6093237
   9  0.9198387  0.6138024
  11  0.9132863  0.5589329
  13  0.9069355  0.5214249
  15  0.9037097  0.4918794
  17  0.9037097  0.4918794
  19  0.8971505  0.4320133
  21  0.8939247  0.4087668
  23  0.8971505  0.4320133

Accuracy was used to select the optimal model using the largest value.
The final value used for the model was k = 9.</code></pre>
</div>
</div>
<p>This returns a series of KNN models and their associated metrics and tells us that the optimal number of nearest neighbors to be considered is 11 and the model accuracy for that K is 0.9198387. That’s good but the Kappa score is 0.6138024, which can indicate that our model is not predicting the two classes with an even accuracy. Because our data is imbalanced (which is common in the real-world) one class is much more frequent than the others. Variables (like cholesterol) drown out other (like BMI). In these cases, overall accuracy becomes misleading because a model can be highly accurate simply by predicting the majority class. How Cohen’s kappa value helps is that it adjusts the agreement that could occur simply due to the majority class, providing a more realistic estimate of the model’s performance.<span class="citation" data-cites="Cadili2025">(<a href="#ref-Cadili2025" role="doc-biblioref"><span>“What Is Cohen’s Kappa? How and When to Use It”</span> 2025</a>)</span></p>
<p>Remember that most of the records in our data set are not patients with diabetes. Our model might simply guess that no patients have diabetes and achieve fairly high accuracy that way.</p>
</section>
<section id="second-knn-model" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="second-knn-model"><span class="header-section-number">3.4</span> Second KNN Model</h2>
<p>We can find that simpler models have better accuracy. To see which variables are having the most impact on our outcome variable, we can use fs.anova to check the analysis of variance for each variable and use that in a second KNN.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>df_stdize<span class="sc">$</span>Diabetes <span class="ot">=</span> <span class="fu">ifelse</span>(df_stdize<span class="sc">$</span>Diabetes <span class="sc">==</span> <span class="st">"Diabetes"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>fs <span class="ot">&lt;-</span> <span class="fu">fs.anova</span>(df_stdize, df_stdize<span class="sc">$</span>Diabetes)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(fs<span class="sc">$</span>fs.order)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Diabetes"        "Glucose"         "Chol.HDL.ratio"  "Cholesterol"    
 [5] "Systolic.BP"     "Waist.hip.ratio" "Weight"          "BMI"            
 [9] "HDL.Chol"        "Diastolic.BP"   </code></pre>
</div>
</div>
<p>We can see that “Glucose” is the most important feature in our data set for predicting diabetes.</p>
<p>We can now do two things here to improve our performance. First, we’ll balance our data set so that we have equal numbers of records with and without diabetes:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>positive_cases <span class="ot">&lt;-</span> <span class="fu">nrow</span>(train_df[train_df<span class="sc">$</span>Diabetes <span class="sc">==</span> <span class="st">'Diabetes'</span>,])</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>balanced <span class="ot">=</span> <span class="fu">rbind</span>(train_df[<span class="fu">sample</span>(<span class="fu">which</span>(train_df<span class="sc">$</span>Diabetes <span class="sc">==</span> <span class="st">'No diabetes'</span>), positive_cases),], train_df[train_df<span class="sc">$</span>Diabetes <span class="sc">==</span> <span class="st">'Diabetes'</span>,])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Second, we’ll use just the Glucose readings to calculate the distance to our ‘neighbors’ in KNN:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>trnctrl_df <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">10</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>model_knn_df_simple <span class="ot">&lt;-</span> <span class="fu">train</span>(Diabetes <span class="sc">~</span> Glucose, <span class="at">data =</span> balanced, <span class="at">method =</span> <span class="st">"knn"</span>, </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">trControl =</span> trnctrl_df, </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">tuneLength =</span> <span class="dv">10</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>model_knn_df_simple</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>k-Nearest Neighbors 

96 samples
 1 predictor
 2 classes: 'Diabetes', 'No diabetes' 

No pre-processing
Resampling: Cross-Validated (10 fold) 
Summary of sample sizes: 87, 86, 86, 86, 88, 86, ... 
Resampling results across tuning parameters:

  k   Accuracy   Kappa    
   5  0.8477778  0.6960976
   7  0.8266667  0.6551916
   9  0.8177778  0.6360976
  11  0.8677778  0.7360976
  13  0.8577778  0.7160976
  15  0.8677778  0.7360976
  17  0.8277778  0.6560976
  19  0.8455556  0.6921429
  21  0.8355556  0.6721429
  23  0.8455556  0.6921429

Accuracy was used to select the optimal model using the largest value.
The final value used for the model was k = 15.</code></pre>
</div>
</div>
<p>The simpler model seems to have better performance. With a K value of 15, we see an accuracy of 0.93 and a Kappa of 0.86. Both of these scores are higher than we had seen with the larger model and the Kappa of 0.86 indicates that we are predicting both classes better although still not perfectly.</p>
</section>
<section id="evaluating-both-knn-models" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="evaluating-both-knn-models"><span class="header-section-number">3.5</span> Evaluating both KNN Models</h2>
Since we held out a testing set of 20% of our training data, we have an easy way to evaluate both of our models. We will pass the model to predict and check the results against the actual test labels. Use a confusion matrix to assess how well our model predicts the test data. To recap, a confusion matrix looks like this:
<center>
<div id="fig-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="confusion-matrix.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Confusion Matrix (Image Source: ©Draelos2019)
</figcaption>
</figure>
</div>
</center>
<section id="unbalanced-model-analysis-and-results" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="unbalanced-model-analysis-and-results"><span class="header-section-number">3.5.1</span> Unbalanced Model Analysis and Results</h3>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>predict_knn <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_knn_df, test_df)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="fu">as.factor</span>(predict_knn), <span class="fu">as.factor</span>(test_df<span class="sc">$</span>Diabetes), <span class="at">positive =</span> <span class="st">"Diabetes"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

             Reference
Prediction    Diabetes No diabetes
  Diabetes           3           0
  No diabetes        9          66
                                          
               Accuracy : 0.8846          
                 95% CI : (0.7922, 0.9459)
    No Information Rate : 0.8462          
    P-Value [Acc &gt; NIR] : 0.220527        
                                          
                  Kappa : 0.3607          
                                          
 Mcnemar's Test P-Value : 0.007661        
                                          
            Sensitivity : 0.25000         
            Specificity : 1.00000         
         Pos Pred Value : 1.00000         
         Neg Pred Value : 0.88000         
             Prevalence : 0.15385         
         Detection Rate : 0.03846         
   Detection Prevalence : 0.03846         
      Balanced Accuracy : 0.62500         
                                          
       'Positive' Class : Diabetes        
                                          </code></pre>
</div>
</div>
<p>Our confusion matrix shows 3 true positives, 66 true negatives, 9 false negatives, and 0 false positives.</p>
<p><strong><em>Sensitivity (0.25000)</em></strong>: The model correctly identifies only 25% of the actual positive cases (high false-negative rate). It only caught 3 out of 12 people who have diabetes and missed 75% of the sick patients. <strong><em>Specificity (1.00000)</em></strong>: The model correctly identifies 100% of the negative cases, meaning there are no false positives. <strong><em>Positive Predictive Value (1.00000)</em></strong>: When the model predicts a positive case, it is 100% correct. <strong><em>Negative Predictive Value (0.88000)</em></strong>: When the model predicts a negative case, it is correct 88% of the time. <strong><em>Balanced Accuracy (0.62500)</em></strong>: The average of sensitivity and specificity, reflecting a mediocre overall performance skewed by the low sensitivity, detailed in. <strong><em>Prevalence (0.15385)</em></strong>: The actual positive cases represent about 15.4% of the total dataset.</p>
<p>At first glance, having a 88.46% accuracy looks great! If you guessed “no diabetes” for each patient, you’d be right 84.62% of the time because the dataset is unbalanced. Our p value is 0.22 which is greater than 0.05, which means our model isn’t statistically better than just guessing “no diabetes” for everyone.Our kappa of 0.36 which isn’t great. It means most of the accuracy is coming from the lopsided nature of the data rather than the model’s predictive power.</p>
<p>In summary, our unbalanced model (first model) does a good job of identifying patients without diabetes but a poor job of identifying patients with diabetes. The model only accurately identifies 25% of the records labeled ‘Diabetes’ so it’s missing the vast majority of actual diabetes cases.</p>
<p>Now we will look at the confusion matrix for our balanced model (second model).</p>
</section>
<section id="balanced-model-analysis-and-results" class="level3" data-number="3.5.2">
<h3 data-number="3.5.2" class="anchored" data-anchor-id="balanced-model-analysis-and-results"><span class="header-section-number">3.5.2</span> Balanced Model Analysis and Results</h3>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>predict_knn_simple <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_knn_df_simple, test_df)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="fu">as.factor</span>(predict_knn_simple), <span class="fu">as.factor</span>(test_df<span class="sc">$</span>Diabetes), <span class="at">positive =</span> <span class="st">"Diabetes"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

             Reference
Prediction    Diabetes No diabetes
  Diabetes          10          10
  No diabetes        2          56
                                          
               Accuracy : 0.8462          
                 95% CI : (0.7467, 0.9179)
    No Information Rate : 0.8462          
    P-Value [Acc &gt; NIR] : 0.57623         
                                          
                  Kappa : 0.5357          
                                          
 Mcnemar's Test P-Value : 0.04331         
                                          
            Sensitivity : 0.8333          
            Specificity : 0.8485          
         Pos Pred Value : 0.5000          
         Neg Pred Value : 0.9655          
             Prevalence : 0.1538          
         Detection Rate : 0.1282          
   Detection Prevalence : 0.2564          
      Balanced Accuracy : 0.8409          
                                          
       'Positive' Class : Diabetes        
                                          </code></pre>
</div>
</div>
<p>Our confusion matrix shows 10 true positives, 56 true negatives, 2 false negatives, and 10 false positives.</p>
<p><strong><em>Sensitivity (83.3%)</em></strong>: Out of 12 people who actually have diabetes, the model caught 10 of them. It only missed 2. <strong><em>Specificity (84.8%)</em></strong>: Out of 66 healthy people, the model correctly identified 56 as healthy. <strong><em>Pos Pred Value</em></strong>: Is 50% — when the model says “Diabetes,” it’s a coin flip whether the person actually has it. <strong><em>Balanced Accuracy (84.1%)</em></strong>: Since it’s high, it shows the model is actually learning to tell the difference between the two classes. <strong><em>Negative Predictive Value (96.5%)</em></strong>: This is excellent for a medical screen. If the model tells a patient they don’t have diabetes, it is almost certainly correct. <strong><em>Kappa (0.5357)</em></strong>: This is much better. It proves the model is doing much better than just randomly guessing based on the majority group.</p>
<p>As we can see, our overall accuracy rate has fallen slightly, but our ability to predict the diabetes label is much much better.This model correctly predicts 10 of the 12 true ‘diabetes’ records. Simple guessing would have missed all 12 sick people, the model found 10 of them. On the negative side though, the model mis-classifies 9 of the 66 ‘no diabetes’ records as ‘diabetes’. This is a downside of training our KNN on a balanced data set: when we introduce new data points from our test set, our model is a little too over-eager to label them ‘diabetes’ when they aren’t.</p>
</section>
</section>
</section>
<section id="conclusion" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Conclusion</h1>
<p>KNN is a powerful tool to predict the classification or numerical value of new data. It’s simple, intuitive, and easy to learn which makes it easy to implement. In our example, we applied the KNN algorithm to a set of patients to determine who has Diabetes and fine-tuned hyperparameters to improve performance. We also learned how you can prepare data for use with KNN by scaling and centering a data set and the different techniques you can use to tune the algorithms.</p>
<!-- -->


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-An2021" class="csl-entry" role="listitem">
An, J. 2021. <span>“Diagram Illustrating Hamming Distance Between Binary Representations of Integers] [Digital Image].”</span>
</div>
<div id="ref-Tembusai2021" class="csl-entry" role="listitem">
<span>“K-Nearest Neighbor with k-Fold Cross Validation and Analytic Hierarchy Process on Data Classification.”</span> 2021. <em>International Journal of Advances in Data and Information Systems</em> 2 (1): 1–8.
</div>
<div id="ref-VisuallyExplained2025" class="csl-entry" role="listitem">
<span>“K-Nearest Neighbors (KNN) in 3 Min.”</span> 2025.
</div>
<div id="ref-xing2020" class="csl-entry" role="listitem">
<span>“Medical Health Big Data Classification Based on KNN Classification Algorithm.”</span> 2020. <em>IEEE Access</em> 8: 28808–19.
</div>
<div id="ref-Nain2023" class="csl-entry" role="listitem">
<span>“Medical Image Prediction for Diagnosis of Breast Cancer Using Machine Learning.”</span> 2021. <em>AIP Conference Preceedings</em> 2853 (1).
</div>
<div id="ref-zhang2018" class="csl-entry" role="listitem">
S. Zhang, M. Zong, X. Li, and R. Wang. 2018. <span>“Efficient kNN Classification with Different Numbers of Nearest Neighbors.”</span> <em>IEEE Transactions on Neural Networks and Learning Systems</em> 29 (5): 1774–85.
</div>
<div id="ref-Schorling1997" class="csl-entry" role="listitem">
Schorling JB, Siegel M, Roach J. 1997. <span>“A Trial of Church-Based Smoking Cessation Interventions for Rural African Americans.”</span> <em>Preventive Medicine</em> 26: 92–101.
</div>
<div id="ref-Cadili2025" class="csl-entry" role="listitem">
<span>“What Is Cohen’s Kappa? How and When to Use It.”</span> 2025.
</div>
<div id="ref-IBM2024" class="csl-entry" role="listitem">
<span>“What Is the k-Nearest Neighbor (KNN) Algorithm?”</span> 2024.
</div>
<div id="ref-Willems1997" class="csl-entry" role="listitem">
Willems JP, DE Hunt, Saunders JT. 1997. <span>“Prevalence of Coronary Heart Disease Risk Factors Among Rural Blacks: A Community-Based Study.”</span> <em>Southern Medical Journal</em> 90: 814–20.
</div>
<div id="ref-zhang2022" class="csl-entry" role="listitem">
Zhang, S. 2022. <span>“Challenges in KNN Classification.”</span> <em>IEEE Transactions on Knowledge and Data Engineering</em> 34 (10): 4663–75.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "&lt;span style='color: #0366D6;'&gt;Using the Machine Learning Algorithm K-Nearest Neighbors to Detect Patients with Diabetes&lt;/span&gt;"</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> |</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co">  A non-parametric supervised learning algorithm&lt;br/&gt;&lt;hr/&gt;</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co">  - Gloria Lowery</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> '`r Sys.Date()`'</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a><span class="co">    link-external-icon: true</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-block-bg: true</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="co">    code-block-border-left: "#31BAE9"</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="co">    code-overflow: wrap</span></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: show</span></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a><span class="an">course:</span><span class="co"> IDC 6940 - Capstone Projects in Data Science</span></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a><span class="an">bibliography:</span><span class="co"> references.bib</span></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a><span class="an">indent:</span><span class="co"> true</span></span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>------</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Presentation</span><span class="co">](link)</span>{.external target="_blank"}</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a><span class="fu"># Introduction</span></span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>When give data we typically want to make sense of what the data is telling us. Machine learning algorithms enable us to do just that. They are mathematical and statistical instructions that computers learn to make sense of a raw dataset. </span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>One such learning algorithm that we will look at is K-Nearest Neighbor. It is considered a "non-parametric supervised learning algorithm." Non-parametric meaning it makes few or no assumptions about the underlying shape or distribution of data. Supervised, as in, it learns from labeled data (input that has a corresponding output) with a goal to predict outcomes for new, unseen data.  </span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a>The main goal of the K-Nearest Neighbors(KNN) algorithm is to predict the classification or numerical value of a new data point based on how similar it is to its closest neighbors. In this paper we will discuss the concept and underlying methodology of KNN, it's strengths and limitations, as well as its real-world applications such as in business and medicine. Specifically, applying the KNN algorithm to identify diabetes within a group of subjects who were studied in order to understand the prevalence of obesity, diabetes, and other cardiovascular risk factors. </span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>You can think of KNN as ***"birds of a feather flock together."*** </span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-36"><a href="#cb21-36" aria-hidden="true" tabindex="-1"></a><span class="fu"># Method</span></span>
<span id="cb21-37"><a href="#cb21-37" aria-hidden="true" tabindex="-1"></a>The K-Nearest Neighbors (KNN) algorithm is one of the simplest and most intuitive supervised machine learning methods used for both classification (assigning a category) and regression (predicting a value). It is a non-parametric, supervised machine learning method used for both classification and regression. It requires two instances for it to achieve its goal 1) a distance metric and 2) defining K<span class="co">[</span><span class="ot">@IBM2024</span><span class="co">]</span>. Its methodology relies on the proximity principle, assuming that similar data points exist in close proximity within a feature space. </span>
<span id="cb21-38"><a href="#cb21-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-39"><a href="#cb21-39" aria-hidden="true" tabindex="-1"></a>Take a look at the following photo. </span>
<span id="cb21-40"><a href="#cb21-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-41"><a href="#cb21-41" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">center</span><span class="dt">&gt;</span></span>
<span id="cb21-42"><a href="#cb21-42" aria-hidden="true" tabindex="-1"></a><span class="al">![K-Nearest Neighbor Visual Representation (Image Source: ©Wikipedia2019)](KnnClassification.svg.png)</span>{#fig-1}</span>
<span id="cb21-43"><a href="#cb21-43" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;/</span><span class="kw">center</span><span class="dt">&gt;</span></span>
<span id="cb21-44"><a href="#cb21-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-45"><a href="#cb21-45" aria-hidden="true" tabindex="-1"></a>When determining how to classify the green dot as either a blue square or red triangle, we will look at its neighbors - specifically the ones closest to it. Here, if we chose to look at three of its closest neighbors (k=3) we are looking at the area within the inner solid circle. We see that the majority of its neighbors are red triangles so we would classify the green dot as a red triangle. However, if we're looking within the area of dashed circle, we see three blue squares vs two red triangles so the green dot would then be classified as a blue square.   </span>
<span id="cb21-46"><a href="#cb21-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-47"><a href="#cb21-47" aria-hidden="true" tabindex="-1"></a>But KNN is a bit more complex than this. </span>
<span id="cb21-48"><a href="#cb21-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-49"><a href="#cb21-49" aria-hidden="true" tabindex="-1"></a><span class="fu">## Core Steps of the KNN Methodology  </span></span>
<span id="cb21-50"><a href="#cb21-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-51"><a href="#cb21-51" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Defining the Parameter 'K': Like mentioned, when defining or selecting k, we are selecting the number of nearest neighbors to consider to determine the classification of a query point. For example, K=1, means it will be assigned to the same class as its single nearest neighbor. Choosing K depends on the input data. For example, data with more outliers performs much better with higher k values. We also want to choose an odd number for k to minimize the chances of ties in classification. <span class="co">[</span><span class="ot">@zhang2018</span><span class="co">]</span></span>
<span id="cb21-52"><a href="#cb21-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-53"><a href="#cb21-53" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Calculating Distance: When a new, unlabeled data point is introduced, the algorithm calculates its distance to every other point in the training dataset. The distance metric measures the distance between the query point(s) and other data points. It can be calculated using a variety of formulas. For example, either Euclidean distance, Manhattan distance, Minkowski, or Hamming distance, and we can visualize this using Voronezh diagrams like above. <span class="co">[</span><span class="ot">@VisuallyExplained2025</span><span class="co">]</span></span>
<span id="cb21-54"><a href="#cb21-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-55"><a href="#cb21-55" aria-hidden="true" tabindex="-1"></a>_Euclidean Distance_: Most commonly used. Measures the "straight-line" path between points; best for continuous data.</span>
<span id="cb21-56"><a href="#cb21-56" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb21-57"><a href="#cb21-57" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-58"><a href="#cb21-58" aria-hidden="true" tabindex="-1"></a>D_{euclidean}(x_1, x_2) = \sqrt{\sum_{i = 1}^{n}{((x_1)_i - (x_2)_i)^2}}</span>
<span id="cb21-59"><a href="#cb21-59" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-60"><a href="#cb21-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-61"><a href="#cb21-61" aria-hidden="true" tabindex="-1"></a>_Manhattan Distance_: Calculates the sum of absolute differences, similar to navigating a grid (taxicab geometry).</span>
<span id="cb21-62"><a href="#cb21-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-63"><a href="#cb21-63" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-64"><a href="#cb21-64" aria-hidden="true" tabindex="-1"></a>D_{manhattan}(x_1, x_2) = \sum_{i = 1}^{n}|((x_1)_i - (x_2)_i)|</span>
<span id="cb21-65"><a href="#cb21-65" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-66"><a href="#cb21-66" aria-hidden="true" tabindex="-1"></a>_Minkowski Distance_: A generalized formula that can represent both Euclidean (p=1) and Manhattan (p=2) distances.</span>
<span id="cb21-67"><a href="#cb21-67" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-68"><a href="#cb21-68" aria-hidden="true" tabindex="-1"></a>D_{Minkowski}(X,Y) = \sum_{i = 1}^{n}|x_i - y_i|^p</span>
<span id="cb21-69"><a href="#cb21-69" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-70"><a href="#cb21-70" aria-hidden="true" tabindex="-1"></a>_Hamming Distance_: Used for categorical or string variables to identify where vectors do not match.</span>
<span id="cb21-71"><a href="#cb21-71" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">center</span><span class="dt">&gt;</span></span>
<span id="cb21-72"><a href="#cb21-72" aria-hidden="true" tabindex="-1"></a>!<span class="co">[</span><span class="ot">Hamming Distance XOR (Image Source: ©An2021. Inspired from [@An2021])</span><span class="co">](Hamming Distance.png)</span>{#fig-2}</span>
<span id="cb21-73"><a href="#cb21-73" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;/</span><span class="kw">center</span><span class="dt">&gt;</span></span>
<span id="cb21-74"><a href="#cb21-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-75"><a href="#cb21-75" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Identify Neighbors: Combining steps 1 and 2. We defined k, we determined distance based on our metric distance formula. Now we sort and select the points with the smallest distance values to the new query point. </span>
<span id="cb21-76"><a href="#cb21-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-77"><a href="#cb21-77" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Aggregate results based on the goal. </span>
<span id="cb21-78"><a href="#cb21-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-79"><a href="#cb21-79" aria-hidden="true" tabindex="-1"></a><span class="ss"> - </span>Classification: The new point is assigned the class that appears most frequently among its k </span>
<span id="cb21-80"><a href="#cb21-80" aria-hidden="true" tabindex="-1"></a> neighbors (majority or plurality voting). Like the example above, we had mostly blue squares within the vicinity to the query point aka the green dot so it is most likely also a blue square. </span>
<span id="cb21-81"><a href="#cb21-81" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb21-82"><a href="#cb21-82" aria-hidden="true" tabindex="-1"></a><span class="ss"> - </span>Regression: The algorithm predicts a continuous value by taking the average (mean) or median of the k</span>
<span id="cb21-83"><a href="#cb21-83" aria-hidden="true" tabindex="-1"></a> neighbors' target values. </span>
<span id="cb21-84"><a href="#cb21-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-85"><a href="#cb21-85" aria-hidden="true" tabindex="-1"></a><span class="fu">## Key Characteristics of KNN</span></span>
<span id="cb21-86"><a href="#cb21-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-87"><a href="#cb21-87" aria-hidden="true" tabindex="-1"></a>Lazy Learner: KNN is considered a "lazy learner" because it does not have a distinct training phase. It simply stores the training data and defers all computation until a prediction is requested.</span>
<span id="cb21-88"><a href="#cb21-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-89"><a href="#cb21-89" aria-hidden="true" tabindex="-1"></a>Non-Parametric: It makes no prior assumptions about the underlying distribution of the data, making it flexible for complex datasets.</span>
<span id="cb21-90"><a href="#cb21-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-91"><a href="#cb21-91" aria-hidden="true" tabindex="-1"></a>Sensitivity to Scale: Because it relies on distance, features with larger magnitudes can disproportionately influence results. Therefore, feature scaling (standardization or normalization) is a critical preprocessing step.<span class="co">[</span><span class="ot">@xing2020</span><span class="co">]</span> </span>
<span id="cb21-92"><a href="#cb21-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-93"><a href="#cb21-93" aria-hidden="true" tabindex="-1"></a>Finding the Optimal 'K': The value of k is often determined using the Elbow Method or Cross-Validation, where multiple k values are tested to find the one that minimizes the error rate without overfitting or underfitting. Analysts typically choose an odd number for k to prevent ties in classification (like if we had equal red triangles and blue squares what then?). In our example, we will be using cross-validation to determine the value of 'k'. In cross validation, the dataset is divided by kfolds. Where at each iteration each fold is used once as test data and the remaining fold is used as training data, the process is repeated until all data is evaluated.</span>
<span id="cb21-94"><a href="#cb21-94" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">@Tembusai2021</span><span class="co">]</span></span>
<span id="cb21-95"><a href="#cb21-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-96"><a href="#cb21-96" aria-hidden="true" tabindex="-1"></a><span class="fu">## Strengths of KNN </span></span>
<span id="cb21-97"><a href="#cb21-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-98"><a href="#cb21-98" aria-hidden="true" tabindex="-1"></a>1.Easy to implement/learn. There are also few hyper parameters - just the distance and k value. </span>
<span id="cb21-99"><a href="#cb21-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-100"><a href="#cb21-100" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>It's also adaptable. It adjusts easily to new training data since all training data is stored into memory. But similarly, because of that, it doesn't scale well. As the data set grows, the algorithm becomes less efficient due to increasing computational complexity, which compromises overall model performance.</span>
<span id="cb21-101"><a href="#cb21-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-102"><a href="#cb21-102" aria-hidden="true" tabindex="-1"></a><span class="fu">## Weaknesses of KNN </span></span>
<span id="cb21-103"><a href="#cb21-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-104"><a href="#cb21-104" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>As mentioned, it can be considered a "lazy algorithm" meaning it stores all training data and defers the computation to the time of classification, increasing memory usage and leads to slower processing compared to other methods of classifying. In other words, it does not build the model beforehand. It instead stores the data and makes predictions on demand. </span>
<span id="cb21-105"><a href="#cb21-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-106"><a href="#cb21-106" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>KNN also has what's called the "Curse of Dimensionality." It does not perform well with high dimensional data inputs. On a 2D xy graph it works fine but if we wanted to classify according to color, size, weight, etc. then the data points become sparse in higher dimensions and the distance between points become too similar for KNN to find meaningful neighbors. This leads to what's called the "peaking phenomenon." The peaking phenomenon occurs after reaching the optimal number of features - any more just increases noise and increases classification errors especially when the sample size is small. Feature selection and dimensionality reduction techniques can help minimize "curse of dimensionality" but we need to be careful. </span>
<span id="cb21-107"><a href="#cb21-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-108"><a href="#cb21-108" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Another weakness is overfitting. Low k values can overfit  the data. High values tend to smooth out prediction values since average values over a greater are or neighborhood. <span class="co">[</span><span class="ot">@zhang2022</span><span class="co">]</span></span>
<span id="cb21-109"><a href="#cb21-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-110"><a href="#cb21-110" aria-hidden="true" tabindex="-1"></a><span class="fu">## Uses of the KNN Algorithm</span></span>
<span id="cb21-111"><a href="#cb21-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-112"><a href="#cb21-112" aria-hidden="true" tabindex="-1"></a>When it comes to uses, we can use the KNN algorithm for simple recommendation systems. Data free processing is most commonly used because it's helpful for data sets with missing values because it estimates values using process called missing data imputation. KNN is actually most often used in finance like stock market forecasting, currency exchange rate, money laundering analysis. But it is also used in health care. For example, risk of heart attacks and prostate cancer by calculating most likely gene expression. In this paper we will apply the KNN algorithm to a data set of potential diabetic patients.<span class="co">[</span><span class="ot">@Nain2023</span><span class="co">]</span> </span>
<span id="cb21-113"><a href="#cb21-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-114"><a href="#cb21-114" aria-hidden="true" tabindex="-1"></a><span class="fu"># Analysis and Results</span></span>
<span id="cb21-115"><a href="#cb21-115" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data Description</span></span>
<span id="cb21-116"><a href="#cb21-116" aria-hidden="true" tabindex="-1"></a>These data sets are courtesy of Dr John Schorling, Department of Medicine, University of Virginia School of Medicine.<span class="co">[</span><span class="ot">@Schorling1997</span><span class="co">]</span></span>
<span id="cb21-117"><a href="#cb21-117" aria-hidden="true" tabindex="-1"></a>The data consist of 19 variables on 403 subjects from 1046 subjects who were interviewed in a study to understand the prevalence of obesity, diabetes, and other cardiovascular risk factors in central Virginia for African Americans. According to Dr John Hong, Diabetes Mellitus Type II (adult onset diabetes) is associated most strongly with obesity. The waist/hip ratio may be a predictor in diabetes and heart disease. DM II is also associated with hypertension - they may both be part of "Syndrome X". The 403 subjects were the ones who were actually screened for diabetes. Glycosolated hemoglobin &gt; 7.0 is usually taken as a positive diagnosis of diabetes. <span class="co">[</span><span class="ot">@Willems1997</span><span class="co">]</span> </span>
<span id="cb21-118"><a href="#cb21-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-119"><a href="#cb21-119" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, include=FALSE}</span></span>
<span id="cb21-120"><a href="#cb21-120" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mt)</span>
<span id="cb21-121"><a href="#cb21-121" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb21-122"><a href="#cb21-122" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(httr)</span>
<span id="cb21-123"><a href="#cb21-123" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb21-124"><a href="#cb21-124" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb21-125"><a href="#cb21-125" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb21-126"><a href="#cb21-126" aria-hidden="true" tabindex="-1"></a><span class="fu">GET</span>(<span class="st">"https://query.data.world/s/qmc5py3qjodoyglqcny7ihdowxwepf?dws=00000"</span>, <span class="fu">write_disk</span>(tf <span class="ot">&lt;-</span> <span class="fu">tempfile</span>(<span class="at">fileext =</span> <span class="st">".xlsx"</span>)))</span>
<span id="cb21-127"><a href="#cb21-127" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">read_excel</span>(tf))</span>
<span id="cb21-128"><a href="#cb21-128" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-129"><a href="#cb21-129" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb21-130"><a href="#cb21-130" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(df))</span>
<span id="cb21-131"><a href="#cb21-131" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-132"><a href="#cb21-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-133"><a href="#cb21-133" aria-hidden="true" tabindex="-1"></a>As shown, we have variables we do not need/want including empty columns. We'll select the non-demographic columns to begin and create a reduced data set. The new table below shows the first 6 rows of our reduced data set. </span>
<span id="cb21-134"><a href="#cb21-134" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb21-135"><a href="#cb21-135" aria-hidden="true" tabindex="-1"></a>df_reduced <span class="ot">&lt;-</span> df[<span class="fu">c</span>(<span class="st">"Diabetes"</span>, <span class="st">"Cholesterol"</span>, <span class="st">"Glucose"</span>, <span class="st">"BMI"</span>, <span class="st">"Waist.hip.ratio"</span>, <span class="st">"HDL.Chol"</span>, <span class="st">"Chol.HDL.ratio"</span>, <span class="st">"Systolic.BP"</span>, <span class="st">"Diastolic.BP"</span>, <span class="st">"Weight"</span>)]</span>
<span id="cb21-136"><a href="#cb21-136" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(df_reduced))</span>
<span id="cb21-137"><a href="#cb21-137" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-138"><a href="#cb21-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-139"><a href="#cb21-139" aria-hidden="true" tabindex="-1"></a>The table below now shows a description of each of our variables to be used. </span>
<span id="cb21-140"><a href="#cb21-140" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, include=FALSE}</span></span>
<span id="cb21-141"><a href="#cb21-141" aria-hidden="true" tabindex="-1"></a>vars <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb21-142"><a href="#cb21-142" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variables =</span> <span class="fu">c</span>(<span class="st">"Diabetes"</span>, <span class="st">"Cholesterol"</span>, <span class="st">"Glucose"</span>, <span class="st">"BMI"</span>, <span class="st">"Waist.hip.ratio"</span>, <span class="st">"HDL.Chol"</span>, <span class="st">"Chol.HDL.ratio"</span>, <span class="st">"Systolic.BP"</span>, <span class="st">"Diastolic.BP"</span>, <span class="st">"Weight"</span>),</span>
<span id="cb21-143"><a href="#cb21-143" aria-hidden="true" tabindex="-1"></a>  <span class="at">Description =</span> <span class="fu">c</span>(<span class="st">"Yes/No"</span>, <span class="st">"Numeric"</span>, <span class="st">"Numeric"</span>, <span class="st">"Numeric"</span>, <span class="st">"Waist to Hip Ratio"</span>,<span class="st">"Numeric"</span>,<span class="st">"Cholesterol to HDL ratio"</span>,<span class="st">"Systolic Blood Pressure"</span>,<span class="st">"Diastolic Blood Pressure"</span>,<span class="st">"Numeric"</span>)</span>
<span id="cb21-144"><a href="#cb21-144" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb21-145"><a href="#cb21-145" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-146"><a href="#cb21-146" aria-hidden="true" tabindex="-1"></a><span class="co">#vars &lt;- bind_rows(vars, df_reduced)</span></span>
<span id="cb21-147"><a href="#cb21-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-148"><a href="#cb21-148" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-149"><a href="#cb21-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-150"><a href="#cb21-150" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb21-151"><a href="#cb21-151" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(vars)</span>
<span id="cb21-152"><a href="#cb21-152" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-153"><a href="#cb21-153" aria-hidden="true" tabindex="-1"></a><span class="fu">## Preparing the Data</span></span>
<span id="cb21-154"><a href="#cb21-154" aria-hidden="true" tabindex="-1"></a>Like mentioned, kNN is sensitive to scaling (of the variables). So it is helpful to first standardize the variables. We do this using the preProcess function of the caret package:</span>
<span id="cb21-155"><a href="#cb21-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-156"><a href="#cb21-156" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb21-157"><a href="#cb21-157" aria-hidden="true" tabindex="-1"></a>preproc_reduced <span class="ot">&lt;-</span> <span class="fu">preProcess</span>(df_reduced[,<span class="dv">2</span><span class="sc">:</span><span class="dv">10</span>], <span class="at">method =</span> <span class="fu">c</span>(<span class="st">"scale"</span>, <span class="st">"center"</span>))</span>
<span id="cb21-158"><a href="#cb21-158" aria-hidden="true" tabindex="-1"></a>df_standardized <span class="ot">&lt;-</span> <span class="fu">predict</span>(preproc_reduced, df_reduced[, <span class="dv">2</span><span class="sc">:</span><span class="dv">10</span>])</span>
<span id="cb21-159"><a href="#cb21-159" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-160"><a href="#cb21-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-161"><a href="#cb21-161" aria-hidden="true" tabindex="-1"></a>Now we have scaled and centered values for our data.frame. </span>
<span id="cb21-162"><a href="#cb21-162" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb21-163"><a href="#cb21-163" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df_standardized)</span>
<span id="cb21-164"><a href="#cb21-164" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-165"><a href="#cb21-165" aria-hidden="true" tabindex="-1"></a>Apply those scaled and centered values to our data using the bind_cols method from dpylr to normalize all of our data.</span>
<span id="cb21-166"><a href="#cb21-166" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb21-167"><a href="#cb21-167" aria-hidden="true" tabindex="-1"></a>df_stdize <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(<span class="at">Diabetes =</span> df_reduced<span class="sc">$</span>Diabetes, df_standardized)</span>
<span id="cb21-168"><a href="#cb21-168" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-169"><a href="#cb21-169" aria-hidden="true" tabindex="-1"></a>Now we have a data set which will work well for KNN! </span>
<span id="cb21-170"><a href="#cb21-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-171"><a href="#cb21-171" aria-hidden="true" tabindex="-1"></a><span class="fu">## Using the KNN Model </span></span>
<span id="cb21-172"><a href="#cb21-172" aria-hidden="true" tabindex="-1"></a>First, we create a test/train split so that we can train a KNN model. </span>
<span id="cb21-173"><a href="#cb21-173" aria-hidden="true" tabindex="-1"></a>We will use the createDataPartition from caret to randomly select 80% of the data to use for the training set and 20% of the data to use for the test set. Then, create two different data frames using partition point returned by createDataPartition.</span>
<span id="cb21-174"><a href="#cb21-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-175"><a href="#cb21-175" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb21-176"><a href="#cb21-176" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb21-177"><a href="#cb21-177" aria-hidden="true" tabindex="-1"></a><span class="co"># "p" indicates how much of the data should go into the first created partition</span></span>
<span id="cb21-178"><a href="#cb21-178" aria-hidden="true" tabindex="-1"></a>param_split<span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(df_stdize<span class="sc">$</span>Diabetes, <span class="at">times =</span> <span class="dv">1</span>, <span class="at">p =</span> <span class="fl">0.8</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb21-179"><a href="#cb21-179" aria-hidden="true" tabindex="-1"></a>train_df <span class="ot">&lt;-</span> df_stdize[param_split, ]</span>
<span id="cb21-180"><a href="#cb21-180" aria-hidden="true" tabindex="-1"></a>test_df <span class="ot">&lt;-</span> df_stdize[<span class="sc">-</span>param_split, ]</span>
<span id="cb21-181"><a href="#cb21-181" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-182"><a href="#cb21-182" aria-hidden="true" tabindex="-1"></a>Now we "train" the KNN. </span>
<span id="cb21-183"><a href="#cb21-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-184"><a href="#cb21-184" aria-hidden="true" tabindex="-1"></a>The trainControl method is a helper function for all the nuances of the KNN train method. It allows you to easily set up the KNN training parameters.</span>
<span id="cb21-185"><a href="#cb21-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-186"><a href="#cb21-186" aria-hidden="true" tabindex="-1"></a><span class="in">```{r,echo=TRUE}</span></span>
<span id="cb21-187"><a href="#cb21-187" aria-hidden="true" tabindex="-1"></a>trnctrl_df <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">10</span>)</span>
<span id="cb21-188"><a href="#cb21-188" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-189"><a href="#cb21-189" aria-hidden="true" tabindex="-1"></a>method: This is the resampling method used. Using "cv" or cross validation. </span>
<span id="cb21-190"><a href="#cb21-190" aria-hidden="true" tabindex="-1"></a>number: The number of folds because we're using cv. </span>
<span id="cb21-191"><a href="#cb21-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-192"><a href="#cb21-192" aria-hidden="true" tabindex="-1"></a>Now we will use all our variables to predict Diabetes. Then specify the training data, that we're training a KNN, and pass the training hyperparameters that we built with trainControl.</span>
<span id="cb21-193"><a href="#cb21-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-194"><a href="#cb21-194" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb21-195"><a href="#cb21-195" aria-hidden="true" tabindex="-1"></a>model_knn_df <span class="ot">&lt;-</span> <span class="fu">train</span>(Diabetes <span class="sc">~</span> ., <span class="at">data =</span> train_df, <span class="at">method =</span> <span class="st">"knn"</span>, </span>
<span id="cb21-196"><a href="#cb21-196" aria-hidden="true" tabindex="-1"></a>                      <span class="at">trControl =</span> trnctrl_df, </span>
<span id="cb21-197"><a href="#cb21-197" aria-hidden="true" tabindex="-1"></a>                      <span class="at">tuneLength =</span> <span class="dv">10</span>)</span>
<span id="cb21-198"><a href="#cb21-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-199"><a href="#cb21-199" aria-hidden="true" tabindex="-1"></a>model_knn_df</span>
<span id="cb21-200"><a href="#cb21-200" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-201"><a href="#cb21-201" aria-hidden="true" tabindex="-1"></a>This returns a series of KNN models and their associated metrics and tells us that the optimal number of nearest neighbors to be considered is 11 and the model accuracy for that K is 0.9198387. </span>
<span id="cb21-202"><a href="#cb21-202" aria-hidden="true" tabindex="-1"></a>That's good but the Kappa score is 0.6138024, which can indicate that our model is not predicting the two classes with an even accuracy.</span>
<span id="cb21-203"><a href="#cb21-203" aria-hidden="true" tabindex="-1"></a>Because our data is imbalanced (which is common in the real-world) one class is much more frequent than the others. Variables (like cholesterol) drown out other (like BMI). In these cases, overall accuracy becomes misleading because a model can be highly accurate simply by predicting the majority class.</span>
<span id="cb21-204"><a href="#cb21-204" aria-hidden="true" tabindex="-1"></a>How Cohen’s kappa value helps is that it adjusts the agreement that could occur simply due to the majority class, providing a more realistic estimate of the model’s performance.<span class="co">[</span><span class="ot">@Cadili2025</span><span class="co">]</span></span>
<span id="cb21-205"><a href="#cb21-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-206"><a href="#cb21-206" aria-hidden="true" tabindex="-1"></a>Remember that most of the records in our data set are not patients with diabetes. Our model might simply guess that no patients have diabetes and achieve fairly high accuracy that way.</span>
<span id="cb21-207"><a href="#cb21-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-208"><a href="#cb21-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-209"><a href="#cb21-209" aria-hidden="true" tabindex="-1"></a><span class="fu">## Second KNN Model  </span></span>
<span id="cb21-210"><a href="#cb21-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-211"><a href="#cb21-211" aria-hidden="true" tabindex="-1"></a>We can find that simpler models have better accuracy. To see which variables are having the most impact on our outcome variable, we can use fs.anova to check the analysis of variance for each variable and use that in a second KNN.</span>
<span id="cb21-212"><a href="#cb21-212" aria-hidden="true" tabindex="-1"></a><span class="in">```{r,echo=TRUE}</span></span>
<span id="cb21-213"><a href="#cb21-213" aria-hidden="true" tabindex="-1"></a>df_stdize<span class="sc">$</span>Diabetes <span class="ot">=</span> <span class="fu">ifelse</span>(df_stdize<span class="sc">$</span>Diabetes <span class="sc">==</span> <span class="st">"Diabetes"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb21-214"><a href="#cb21-214" aria-hidden="true" tabindex="-1"></a>fs <span class="ot">&lt;-</span> <span class="fu">fs.anova</span>(df_stdize, df_stdize<span class="sc">$</span>Diabetes)</span>
<span id="cb21-215"><a href="#cb21-215" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(fs<span class="sc">$</span>fs.order)</span>
<span id="cb21-216"><a href="#cb21-216" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-217"><a href="#cb21-217" aria-hidden="true" tabindex="-1"></a>We can see that "Glucose" is the most important feature in our data set for predicting diabetes.</span>
<span id="cb21-218"><a href="#cb21-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-219"><a href="#cb21-219" aria-hidden="true" tabindex="-1"></a>We can now do two things here to improve our performance. First, we'll balance our data set so that we have equal numbers of records with and without diabetes: </span>
<span id="cb21-220"><a href="#cb21-220" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb21-221"><a href="#cb21-221" aria-hidden="true" tabindex="-1"></a>positive_cases <span class="ot">&lt;-</span> <span class="fu">nrow</span>(train_df[train_df<span class="sc">$</span>Diabetes <span class="sc">==</span> <span class="st">'Diabetes'</span>,])</span>
<span id="cb21-222"><a href="#cb21-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-223"><a href="#cb21-223" aria-hidden="true" tabindex="-1"></a>balanced <span class="ot">=</span> <span class="fu">rbind</span>(train_df[<span class="fu">sample</span>(<span class="fu">which</span>(train_df<span class="sc">$</span>Diabetes <span class="sc">==</span> <span class="st">'No diabetes'</span>), positive_cases),], train_df[train_df<span class="sc">$</span>Diabetes <span class="sc">==</span> <span class="st">'Diabetes'</span>,])</span>
<span id="cb21-224"><a href="#cb21-224" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-225"><a href="#cb21-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-226"><a href="#cb21-226" aria-hidden="true" tabindex="-1"></a>Second, we'll use just the Glucose readings to calculate the distance to our 'neighbors' in KNN: </span>
<span id="cb21-227"><a href="#cb21-227" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb21-228"><a href="#cb21-228" aria-hidden="true" tabindex="-1"></a>trnctrl_df <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">10</span>)</span>
<span id="cb21-229"><a href="#cb21-229" aria-hidden="true" tabindex="-1"></a>model_knn_df_simple <span class="ot">&lt;-</span> <span class="fu">train</span>(Diabetes <span class="sc">~</span> Glucose, <span class="at">data =</span> balanced, <span class="at">method =</span> <span class="st">"knn"</span>, </span>
<span id="cb21-230"><a href="#cb21-230" aria-hidden="true" tabindex="-1"></a>                             <span class="at">trControl =</span> trnctrl_df, </span>
<span id="cb21-231"><a href="#cb21-231" aria-hidden="true" tabindex="-1"></a>                             <span class="at">tuneLength =</span> <span class="dv">10</span>)</span>
<span id="cb21-232"><a href="#cb21-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-233"><a href="#cb21-233" aria-hidden="true" tabindex="-1"></a>model_knn_df_simple</span>
<span id="cb21-234"><a href="#cb21-234" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-235"><a href="#cb21-235" aria-hidden="true" tabindex="-1"></a>The simpler model seems to have better performance. With a K value of 15, we see an accuracy of 0.93 and a Kappa of 0.86. </span>
<span id="cb21-236"><a href="#cb21-236" aria-hidden="true" tabindex="-1"></a>Both of these scores are higher than we had seen with the larger model and the Kappa of 0.86 indicates that we are predicting both classes better although still not perfectly.</span>
<span id="cb21-237"><a href="#cb21-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-238"><a href="#cb21-238" aria-hidden="true" tabindex="-1"></a><span class="fu">## Evaluating both KNN Models</span></span>
<span id="cb21-239"><a href="#cb21-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-240"><a href="#cb21-240" aria-hidden="true" tabindex="-1"></a>Since we held out a testing set of 20% of our training data, we have an easy way to evaluate both of our models. We will pass the model to predict and check the results against the actual test labels. Use a confusion matrix to assess how well our model predicts the test data. To recap, a confusion matrix looks like this: </span>
<span id="cb21-241"><a href="#cb21-241" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">center</span><span class="dt">&gt;</span></span>
<span id="cb21-242"><a href="#cb21-242" aria-hidden="true" tabindex="-1"></a><span class="al">![Confusion Matrix (Image Source: ©Draelos2019)](confusion-matrix.png)</span>{#fig-3}</span>
<span id="cb21-243"><a href="#cb21-243" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;/</span><span class="kw">center</span><span class="dt">&gt;</span></span>
<span id="cb21-244"><a href="#cb21-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-245"><a href="#cb21-245" aria-hidden="true" tabindex="-1"></a><span class="fu">### Unbalanced Model Analysis and Results</span></span>
<span id="cb21-246"><a href="#cb21-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-247"><a href="#cb21-247" aria-hidden="true" tabindex="-1"></a><span class="in">```{r,echo=TRUE}</span></span>
<span id="cb21-248"><a href="#cb21-248" aria-hidden="true" tabindex="-1"></a>predict_knn <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_knn_df, test_df)</span>
<span id="cb21-249"><a href="#cb21-249" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="fu">as.factor</span>(predict_knn), <span class="fu">as.factor</span>(test_df<span class="sc">$</span>Diabetes), <span class="at">positive =</span> <span class="st">"Diabetes"</span>)</span>
<span id="cb21-250"><a href="#cb21-250" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-251"><a href="#cb21-251" aria-hidden="true" tabindex="-1"></a>Our confusion matrix shows 3 true positives, 66 true negatives, 9 false negatives, and 0 false positives. </span>
<span id="cb21-252"><a href="#cb21-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-253"><a href="#cb21-253" aria-hidden="true" tabindex="-1"></a>***Sensitivity (0.25000)***: The model correctly identifies only 25% of the actual positive cases (high false-negative rate). It only caught 3 out of 12 people who have diabetes and missed 75% of the sick patients. </span>
<span id="cb21-254"><a href="#cb21-254" aria-hidden="true" tabindex="-1"></a>***Specificity (1.00000)***: The model correctly identifies 100% of the negative cases, meaning there are no false positives.</span>
<span id="cb21-255"><a href="#cb21-255" aria-hidden="true" tabindex="-1"></a>***Positive Predictive Value (1.00000)***: When the model predicts a positive case, it is 100% correct.</span>
<span id="cb21-256"><a href="#cb21-256" aria-hidden="true" tabindex="-1"></a>***Negative Predictive Value (0.88000)***: When the model predicts a negative case, it is correct 88% of the time.</span>
<span id="cb21-257"><a href="#cb21-257" aria-hidden="true" tabindex="-1"></a>***Balanced Accuracy (0.62500)***: The average of sensitivity and specificity, reflecting a mediocre overall performance skewed by the low sensitivity, detailed in.</span>
<span id="cb21-258"><a href="#cb21-258" aria-hidden="true" tabindex="-1"></a>***Prevalence (0.15385)***: The actual positive cases represent about 15.4% of the total dataset. </span>
<span id="cb21-259"><a href="#cb21-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-260"><a href="#cb21-260" aria-hidden="true" tabindex="-1"></a>At first glance, having a 88.46% accuracy looks great! If you guessed "no diabetes" for each patient, you'd be right 84.62% of the time because the dataset is unbalanced. Our p value is 0.22 which is greater than 0.05, which means our model isn't statistically better than just guessing "no diabetes" for everyone.Our kappa of 0.36 which isn't great. It means most of the accuracy is coming from the lopsided nature of the data rather than the model's predictive power. </span>
<span id="cb21-261"><a href="#cb21-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-262"><a href="#cb21-262" aria-hidden="true" tabindex="-1"></a>In summary, our unbalanced model (first model) does a good job of identifying patients without diabetes but a poor job of identifying patients with diabetes. The model only accurately identifies 25% of the records labeled 'Diabetes' so it's missing the vast majority of actual diabetes cases. </span>
<span id="cb21-263"><a href="#cb21-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-264"><a href="#cb21-264" aria-hidden="true" tabindex="-1"></a>Now we will look at the confusion matrix for our balanced model (second model). </span>
<span id="cb21-265"><a href="#cb21-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-266"><a href="#cb21-266" aria-hidden="true" tabindex="-1"></a><span class="fu">### Balanced Model Analysis and Results </span></span>
<span id="cb21-267"><a href="#cb21-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-268"><a href="#cb21-268" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb21-269"><a href="#cb21-269" aria-hidden="true" tabindex="-1"></a>predict_knn_simple <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_knn_df_simple, test_df)</span>
<span id="cb21-270"><a href="#cb21-270" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="fu">as.factor</span>(predict_knn_simple), <span class="fu">as.factor</span>(test_df<span class="sc">$</span>Diabetes), <span class="at">positive =</span> <span class="st">"Diabetes"</span>)</span>
<span id="cb21-271"><a href="#cb21-271" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-272"><a href="#cb21-272" aria-hidden="true" tabindex="-1"></a>Our confusion matrix shows 10 true positives, 56 true negatives, 2 false negatives, and 10 false positives. </span>
<span id="cb21-273"><a href="#cb21-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-274"><a href="#cb21-274" aria-hidden="true" tabindex="-1"></a>***Sensitivity (83.3%)***: Out of 12 people who actually have diabetes, the model caught 10 of them. It only missed 2.</span>
<span id="cb21-275"><a href="#cb21-275" aria-hidden="true" tabindex="-1"></a>***Specificity (84.8%)***: Out of 66 healthy people, the model correctly identified 56 as healthy.</span>
<span id="cb21-276"><a href="#cb21-276" aria-hidden="true" tabindex="-1"></a>***Pos Pred Value***: Is 50% — when the model says "Diabetes," it’s a coin flip whether the person actually has it.</span>
<span id="cb21-277"><a href="#cb21-277" aria-hidden="true" tabindex="-1"></a>***Balanced Accuracy (84.1%)***: Since it’s high, it shows the model is actually learning to tell the difference between the two classes.</span>
<span id="cb21-278"><a href="#cb21-278" aria-hidden="true" tabindex="-1"></a>***Negative Predictive Value (96.5%)***: This is excellent for a medical screen. If the model tells a patient they don't have diabetes, it is almost certainly correct.</span>
<span id="cb21-279"><a href="#cb21-279" aria-hidden="true" tabindex="-1"></a>***Kappa (0.5357)***: This is much better. It proves the model is doing much better than just randomly guessing based on the majority group.</span>
<span id="cb21-280"><a href="#cb21-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-281"><a href="#cb21-281" aria-hidden="true" tabindex="-1"></a>As we can see, our overall accuracy rate has fallen slightly, but our ability to predict the diabetes label is much much better.This model correctly predicts 10 of the 12 true 'diabetes' records. Simple guessing would have missed all 12 sick people, the model found 10 of them. On the negative side though, the model mis-classifies 9 of the 66 'no diabetes' records as 'diabetes'. This is a downside of training our KNN on a balanced data set: when we introduce new data points from our test set, our model is a little too over-eager to label them 'diabetes' when they aren't.</span>
<span id="cb21-282"><a href="#cb21-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-283"><a href="#cb21-283" aria-hidden="true" tabindex="-1"></a><span class="fu"># Conclusion</span></span>
<span id="cb21-284"><a href="#cb21-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-285"><a href="#cb21-285" aria-hidden="true" tabindex="-1"></a>KNN is a powerful tool to predict the classification or numerical value of new data. It's simple, intuitive, and easy to learn which makes it easy to implement. In our example, we applied the KNN algorithm to a set of patients to determine who has Diabetes and fine-tuned hyperparameters to improve performance. We also learned how you can prepare data for use with KNN by scaling and centering a data set and the different techniques you can use to tune the algorithms.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>